### Locals
@HOST = localhost:3000

### Journal

# @name createJournal
# @prompt journalDate date of journal in YYYY-MM-DD format
# @prompt html html content of journal entry
# @prompt lexical lexical state of journal entry
# @prompt mood mood of journal entry, it can be DEPRESSED, STRESS, RELAXED or MOTIVATED
POST /api/journal HTTP/1.1
Host: {{HOST}}
Accept: application/json, text/html
Content-Type: application/json

{
    "journalDate": "{{journalDate}}",
    "html": "{{html}}",
    "lexical": "{{lexical}}",
    "mood": "{{mood}}"
}

### 

# @name getJournal
# @prompt id id of journal entry
GET /api/journal?id={{id}} HTTP/1.1
Host: {{HOST}}

###

# @name getJournals
GET /api/journals HTTP/1.1
Host: {{HOST}}

###

# @name updateJournal
# @prompt id id of journal entry
# @prompt html html content of journal entry
# @prompt lexical lexical state of journal entry
# @prompt mood mood of journal entry, it can be DEPRESSED, STRESS, RELAXED or MOTIVATED
POST /api/journal/update?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "html": "{{html}}",
    "lexical": "{{lexical}}",
    "mood": "{{mood}}"
}

###

# @name deleteJournal
# @prompt id id of journal entry
DELETE /api/journal?id={{id}} HTTP/1.1
Host: {{HOST}}

### Task

# @name createTask
# @prompt description description of task
# @prompt dueDate (optional) due date of task in Date() or ISO format
# @prompt status (optional) status of task: TODO or DONE
# @prompt journalId (optional) id of journal entry
# @prompt milestoneId (optional) id of milestone
POST /api/task HTTP/1.1
Host: {{HOST}}

{
    "description": "{{description}}",
    "dueDate": "{{dueDate}}",
    "status": "{{status}}",
    "journalId": "{{journalId}}",
    "milestoneId": "{{milestoneId}}"
}

###

# @name getTask
# @prompt id id of task
GET /api/task?id={{id}} HTTP/1.1
Host: {{HOST}}

###

# @name getTasks
# INFO: filters and sort are optional (it'll return all tasks if not provided)
# CAVEAT: because it has a body, it must be a POST request,
#         Nuxt/H3 doesn't let me do a GET request with a body, so ya...
POST /api/tasks HTTP/1.1
Host: {{HOST}}

{
    "filters": {
        "journalId": 1
    },
    "sort": {
        "createdAt": "desc"
    }
}

###

# @name updateTask
# @prompt id id of task
# NOTE: if any of the field is not provided, it will not be updated
# @prompt description (optional) description of task
# @prompt dueDate (optional) due date of task in Date() or ISO format
# @prompt status (optional) status of task: TODO or DONE
# @prompt journalId (optional) id of journal entry
# @prompt milestoneId (optional) id of milestone
POST /api/task/update?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "description": "{{description}}",
    "dueDate": "{{dueDate}}",
    "status": "{{status}}",
    "journalId": {{journalId}},
    "milestoneId": {{milestoneId}}
}

###

# @name deleteTask
# @prompt id id of task
DELETE /api/task?id={{id}} HTTP/1.1
Host: {{HOST}}

### Milestone

# @name createMilestone
# @prompt description description of milestone
# @prompt status (optional) status of milestone: INPROGRESS or COMPLETED
# @prompt journalId id of journal entry
POST /api/milestone HTTP/1.1
Host: {{HOST}}

{
    "description": "{{description}}",
    "status": "{{status}}",
    "to": {
        "journalId": "{{journalId}}"
    }
}

###

# @name createMilestoneAndTagTask
# @prompt description description of milestone
# @prompt status (optional) status of milestone: INPROGRESS or COMPLETED
# @prompt journalId id of journal entry
# @prompt taskId id of task
POST /api/milestone HTTP/1.1
Host: {{HOST}}

{
    "description": "{{description}}",
    "status": "{{status}}",
    "to": {
        "journalId": "{{journalId}}",
        "taskId": "{{taskId}}"
    }
}

###

# @name createMilestoneAndCreateTask
# @prompt description description of milestone
# @prompt journalId id of journal entry
# @prompt description description of task
# @prompt status (optional) status of milestone: INPROGRESS or COMPLETED
# @prompt dueDate (optional) due date of task in Date() or ISO format
# @prompt taskStatus (optional) status of task: TODO or DONE
POST /api/milestone HTTP/1.1
Host: {{HOST}}

{
    "description": "{{description}}",
    "status": "{{status}}",
    "to": {
        "journalId": "{{journalId}}"
    },
    "create": {
        "task": {
            "description": "{{description}}",
            "dueDate": "{{dueDate}}",
            "status": "{{taskStatus}}"
        }
    }
}

###

# @name getMilestone
# @prompt milestoneId id of milestone
GET /api/milestone?id={{milestoneId}} HTTP/1.1
Host: {{HOST}}

###

# @name getMilestones
POST /api/milestones HTTP/1.1
Host: {{HOST}}

{
    "filters": {
        "journalId": 2,
        "status": "INPROGRESS"
    },
    "sort": {
        "createdAt": "asc"
    }
}

###

# @name updateMilestone
# @prompt id id of milestone
# @prompt description updated description of milestone
# @prompt status (optional) status of milestone: INPROGRESS or COMPLETED
POST /api/milestone/update?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "description": "{{description}}",
    "status": "{{status}}"
}

###

# @name deleteMilestone
# @prompt id id of milestone
DELETE /api/milestone?id={{id}} HTTP/1.1
Host: {{HOST}}

###

# @name tagMilestoneToTask
# @prompt id id of milestone
# @prompt taskId id of task
POST /api/milestone/tag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "to": {
        "taskId": "{{taskId}}"
    }
}

###

# @name tagMilestoneToJournal
# @prompt id id of milestone
# @prompt journalId id of journal
POST /api/milestone/tag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "to": {
        "journalId": "{{journalId}}"
    }
}

###

# @name tagMilestoneToTaskAndJournal
# @prompt id id of milestone
# @prompt taskId id of task
# @prompt journalId id of journal
POST /api/milestone/tag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "to": {
        "taskId": "{{taskId}}",
        "journalId": "{{journalId}}"
    }
}

###

# @name tagMilestoneToNewTaskAndJournal
# @prompt id id of milestone
# @prompt journalId id of journal
# @prompt description description of task
# @prompt dueDate (optional) due date of task in Date() or ISO format
# @prompt status (optional) status of task: TODO or DONE
# NOTE: You cannot tag an existing and create it at the same time, 
# don't break natural order of things
POST /api/milestone/tag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "to": {
        "journalId": "{{journalId}}"
    },
    "create": {
        "task": {
            "description": "{{description}}",
            "dueDate": "{{dueDate}}",
            "status": "{{status}}"
        }
    }
}

###

# @name untagMilestoneFromTask
# @prompt id id of milestone
# @prompt taskId id of task
POST /api/milestone/untag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "from": {
        "taskId": "{{taskId}}"
    }
}

###

# @name untagMilestoneFromJournal
# @prompt id id of milestone
# @prompt journalId id of journal
POST /api/milestone/untag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "from": {
        "journalId": "{{journalId}}"
    }
}

###

# @name untagMilestoneFromTaskAndJournal
# @prompt id id of milestone
# @prompt taskId id of task
# @prompt journalId id of journal
POST /api/milestone/untag?id={{id}} HTTP/1.1
Host: {{HOST}}

{
    "from": {
        "taskId": "{{taskId}}",
        "journalId": "{{journalId}}"
    }
}
