version: "3"
services:
  mysql:
    user: mysql
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - .dockervolume/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -ppass
