version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'student-life.live -> http://172.17.0.1:3000'
      STAGE: 'production' # Don't use production until staging works
    volumes:
      - .dockervolume/https-portal:/var/lib/https-portal
