version: "3"
services:
  mysql-test:
    user: mysql
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    healthcheck:
      test: mysqladmin ping -ppass
