name: deploy

on:
  push:
    branches:
      - 'test-deploy-to-azure-vm'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            pm2 stop student-life
            cd ~/student-life
            git pull
            npm install
            npx prisma migrate dev
            pm2 start "npm run dev" --name student-life
